apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-07-26T14:24:46Z"
  generation: 2
  labels:
    app: alpaca-prod
    env: prod
    ver: "1"
  name: alpaca-prod
  namespace: default
  resourceVersion: "60676"
  uid: 3377e9a6-de05-4908-b722-3c423c2ee7af
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alpaca-prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alpaca-prod
    spec:
      containers:
      - env:
        - name: FOO
          value: BAR
        image: gcr.io/kuar-demo/kuard-amd64:blue
        imagePullPolicy: IfNotPresent
        name: kuard-amd64
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-07-26T15:28:09Z"
    lastUpdateTime: "2021-07-26T15:28:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-26T14:24:46Z"
    lastUpdateTime: "2021-07-26T15:41:02Z"
    message: ReplicaSet "alpaca-prod-5d5fbfbccc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
