apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-26T14:28:00Z"
  labels:
    app: alpaca-prod
    env: prod
    ver: "1"
  name: alpaca-prod
  namespace: default
  resourceVersion: "60126"
  uid: 15d38b08-3e5c-4e06-8f6e-1a855e2d429f
spec:
  clusterIP: 10.109.29.211
  clusterIPs:
  - 10.109.29.211
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alpaca-prod-new
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
